# Site settings
title: HsquaredDesign
email: howardhosokawa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
# plugins: 
#   - jekyll-paginate
# paginate: 2
# paginate_path: "/blog/page:num/"
# /portfolio/

plugins:
  - jekyll-redirect-from
    
collections:
  home:
    output: true
    permalink: /home/:path/
  portfolio:
    output: true
    permalink: /portfolio/:path/
  resume:
    output: true
    permalink: /resume/:path/
  about:
    output: true
    permalink: /about/:path/


